# Generated by Django 6.0.4 on 2026-04-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='field',
            name='planting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='stage',
            field=models.CharField(choices=[('PLANTED', 'Planted'), ('GROWING', 'Growing'), ('READY', 'Ready'), ('HARVESTED', 'Harvested')], default='READY', max_length=20),
        ),
    ]
